### ISSUE TITLE
Implement services section

### ISSUE THREAD

**Issue by SP-XD** [SP-XD/sp-xd.github.io#4]
First propose a design and idea for the services section.

Some guidelines:
1. the section will comprise of cards and titles like App developer, Web developer or Catchy titles like Want to build a app? or website?
2. When you click on the card
   1. Either it expands, or a popup dialog box appears and shows previous projects and what tech stack we are using.
   2. at the end there will be a contact button 

This are just for reference, feel free to add your ideas below or show some Screen shots after building locally

**Comment by tejus0** [comment]
Hey @SP-XD I have an idea for your services section like there can be various cards like webapp development which will include the categories in which you ask the user which type of webapp they want like ecommerce website , static informative website or any service like website maintainance . 
Similarly other card for APP development which will include various categories of it . 
There can be many other cards also depending the skills you add . And at last the " OTHER SERVICES" card which will be helpful for a user who wants customised services blonging multiple categories . 
So please assign me this task under hacktoberfest so that i can contribute in your awesome website .

**Comment by SP-XD** [comment]
> Hey @SP-XD I have an idea for your services section like there can be various cards like webapp development which will include the categories in which you ask the user which type of webapp they want like ecommerce website , static informative website or any service like website maintainance . Similarly other card for APP development which will include various categories of it . There can be many other cards also depending the skills you add . And at last the " OTHER SERVICES" card which will be helpful for a user who wants customised services blonging multiple categories . So please assign me this task under hacktoberfest so that i can contribute in your awesome website .

great idea @tejus0, I am assigning you

**Comment by tejus0** [comment]
Hey @SP-XD I have made the services section , but i am facing difficulty to push it in your default branch "beta ". So how to push it please tell me . It is showing me that " You don't have permissions to push to 'SP-XD/sp-xd' on GitHub " . And it is also giving same error when i am forking .

**Comment by SP-XD** [comment]
> Hey @SP-XD I have made the services section , but i am facing difficulty to push it in your default branch "beta ". So how to push it please tell me . It is showing me that " You don't have permissions to push to 'SP-XD/sp-xd' on GitHub " . And it is also giving same error when i am forking .

Umm I think you are new to this. You can't push directly in my repository sp-xd/sp-xd. You have to push your code in the fork you created from my repository. Then you have to open a Pull Request so that I can see what changes you have made and then I can merge it in my repository if I find the Pull Request is ready for merging. Please go through YouTube tutorials on how to work with git to better understand.

**Comment by SP-XD** [comment]
#12 added initial services section.
But its not polished, If anyone wants to work on it. Can do so!
